### ISSUE TITLE
Failed to build.

### ISSUE THREAD

**Issue by GOGOYAO** [SequoiaDB/sequoiasql-mysql#46]
I follow the steps in https://github.com/SequoiaDB/sequoiasql-mysql and run `cmake XXXXX`. I get error as follows.

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
SDB_DYNAMIC_LIBRARY
    linked by target "sql" in directory /home/users/gg/workspace/mysql-5.7.24/sql
    linked by target "mysqlserver" in directory
    /home/users/gg/workspace/mysql-5.7.24/libmysqld
SDB_INCLUDE_DIR
    used as include directory in directory
    /home/users/gg/workspace/mysql-5.7.24/storage/sequoiadb
    used as include directory in directory
    /home/users/gg/workspace/mysql-5.7.24/storage/sequoiadb
    used as include directory in directory
    /home/users/gg/workspace/mysql-5.7.24/storage/sequoiadb
    used as include directory in directory
    /home/users/gg/workspace/mysql-5.7.24/storage/sequoiadb
    used as include directory in directory
    /home/users/gg/workspace/mysql-5.7.24/storage/sequoiadb
    used as include directory in directory
    /home/users/gg/workspace/mysql-5.7.24/storage/sequoiadb
    used as include directory in directory
    /home/users/gg/workspace/mysql-5.7.24/storage/sequoiadb
    used as include directory in directory
    /home/users/gg/workspace/mysql-5.7.24/storage/sequoiadb
    used as include directory in directory
    /home/users/gg/workspace/mysql-5.7.24/storage/sequoiadb
    used as include directory in directory
    /home/users/gg/workspace/mysql-5.7.24/storage/sequoiadb
    used as include directory in directory
    /home/users/gg/workspace/mysql-5.7.24/storage/sequoiadb
```
So, how should I set SDB_INCLUDE_DIR and SDB_DYNAMIC_LIBRARY? Do I need install sequoiadb or build sequoiadb by myself at first? I have download the source code of sequoiadb to my directory.

**Comment by shanks2048** [comment]
My building enviroment is as below:

[root@SdbTest001 mysql_src]# pwd
/opt/mysql_src
[root@SdbTest001 mysql_src]# ls
boost_1_59_0  mysql-5.7.25  readme.txt
[root@SdbTest001 mysql_src]# cat readme.txt 
﻿cmake . -DWITH_BOOST=/opt/mysql_src/boost_1_59_0/ -DWITH_SDB_DRIVER=/opt/mysql_src/mysql-5.7.25/storage/sequoiadb/sequoiadb  -DCMAKE_INSTALL_PREFIX=/opt/sequoiasql/mysql -DMYSQL_DATADIR=/opt/sequoiasql/mysql/data -DCMAKE_BUILD_TYPE=Release -DSDB_DRIVER_VERSION=3.2.1 -DSDB_PLUGIN_VERSION=ce024c0 in dir /opt/mysql_src/mysql-5.7.25

make -j 4

make install
[root@SdbTest001 mysql_src]# 
[root@SdbTest001 mysql_src]# ll /opt/mysql_src/mysql-5.7.25/storage/sequoiadb/sequoiadb
total 8
drwxr-xr-x 3 root root 4096 Jul 10 16:47 include
drwxr-xr-x 2 root root 4096 May 30 16:08 lib
[root@SdbTest001 mysql_src]# 

I get  include and lib dir from /opt/sequoiadb/include and /opt/sequoiadb/lib。I install the sequoaidb from the sequoiadb.xxxx.run in the path /opt/sequoiadb. To build the sequoiasql-mysql we need the get c++ driver, and, we can get it from http://download.sequoiadb.com/cn/driver .  I hope it can help you.

**Comment by GoGoYao** [comment]
I download the c++ driver from http://download.sequoiadb.com/cn/driver and I get a `include` and `lib` directory after uncompress the C&CPP-3.2.3-linux_x86_64.tar.gz. And then I set the variables as follows. 
```
export SDB_INCLUDE_DIR=/home/users/aa/workspace/C\&CPP-3.2.3-linux_x86_64/include/ && export SDB_DYNAMIC_LIBRARY=/home/users/aa/workspace/C\&CPP-3.2.3-linux_x86_64/lib/
```
And then I run cmake as follows.
```
cmake . -DWITH_BOOST=/home/users/aa/workspace/mysql-5.7.24/boost/boost_1_59_0/ -DCMAKE_INSTALL_PREFIX=/home/users/aa/mysql -DMYSQL_DATADIR=/home/users/aa/mysql/data -DWITH_SDB_DRIVER=/home/users/aa/workspace/mysql-5.7.24/storage/sequoiadb -DCMAKE_BUILD_TYPE=Release
```
But I get the same error, that is `CMake Error: The following variables are used in this project, but they are set to NOTFOUND.`

**Comment by shengyunyao** [comment]
Thank you, I will try it again
