### ISSUE TITLE
Failed to create table

### ISSUE THREAD

**Issue by GoGoYao** [SequoiaDB/sequoiasql-mysql#47]
I install SequoiaDB following steps in http://doc.sequoiadb.com/cn/sequoiadb-cat_id-1521595270-edition_id-0. And then I use `bin/mysql -S database/3306/mysqld.sock -u root` to login. But when I tried to create table by `create table cl(a int, b int, c text, primary key(a, b) ) ;`, one error happened as follows.
```
ERROR 1030 (HY000): Got error 157 from storage engine
```
Please help me out.
Thank you

**Comment by GoGoYao** [comment]
status of instance is as follows,
```
$ bin/sdb_sql_ctl status
INSTANCE   PID        SVCNAME    SQLDATA                                  SQLLOG
myinst     20145      -          /home/work/sequoiadb-mysql/database/3306/ /home/work/sequoiadb-mysql/myinst.log
Total: 1; Run: 1
```

**Comment by shanks2048** [comment]
We can get the error message from http://doc.sequoiadb.com/cn/sequoiadb-cat_id-1555382544-edition_id-0
-157 means "Invalid node configuration". Your sequoiadb cluster may have not been successfully built up yet. 
Do you compile the SequoiaDB by yourself? Or to use the sequoiadb.xxxx.run to install the SequoiaDB?
You can reference http://doc.sequoiadb.com/cn/sequoiadb-cat_id-1432190609-edition_id-0 to make sure you have had a working cluster(not standalone) of SequoiaDB. 
If your cluster does not work, please reference http://doc.sequoiadb.com/cn/sequoiadb-cat_id-1432191002-edition_id-0 to build it up. Or you can reference "Quick Start"(http://doc.sequoiadb.com/cn/sequoiadb-cat_id-1519612914-edition_id-0 ) to build it up.



> I install SequoiaDB following steps in http://doc.sequoiadb.com/cn/sequoiadb-cat_id-1521595270-edition_id-0. And then I use `bin/mysql -S database/3306/mysqld.sock -u root` to login. But when I tried to create table by `create table cl(a int, b int, c text, primary key(a, b) ) ;`, one error happened as follows.
> 
> ```
> ERROR 1030 (HY000): Got error 157 from storage engine
> ```
> 
> Please help me out.
> Thank you

We can get the error message from http://doc.sequoiadb.com/cn/sequoiadb-cat_id-1555382544-edition_id-0
-157 means "Invalid node configuration". Your sequoiadb cluster may have not been successfully built up yet. 
Do you compile the SequoiaDB by yourself? Or to use the sequoiadb.xxxx.run to install the SequoiaDB?
You can reference http://doc.sequoiadb.com/cn/sequoiadb-cat_id-1432190609-edition_id-0 to make sure you have had a working cluster(not standalone) of SequoiaDB. 
If your cluster does not work, please reference http://doc.sequoiadb.com/cn/sequoiadb-cat_id-1432191002-edition_id-0 to build it up. Or you can reference "Quick Start"(http://doc.sequoiadb.com/cn/sequoiadb-cat_id-1519612914-edition_id-0 ) to build it up.

**Comment by GoGoYao** [comment]
Do you mean that if I use mysql I can not use standalone?

**Comment by GoGoYao** [comment]
> Do you mean that if I use mysql I can not use standalone?

I have tried it and it works. Thank you for your help
