### ISSUE TITLE
MySQL error code 1015 (ER_CANT_LOCK): Can't lock file (errno: %d - %s)

### ISSUE THREAD

**Issue by GOGOYAO** [SequoiaDB/sequoiasql-mysql#48]
Hi, I use sequoiasql-mysql and build a standalone SequoiaDB. I can create tables but when I insert data into the table as follows, the error occured.
```
insert into cl values(1, 101, "SequoiaDB test");
```
Error is `MySQL error code 1015 (ER_CANT_LOCK): Can't lock file (errno: %d - %s)`.
Please help me out.

**Comment by GoGoYao** [comment]
I use sequoiadb-3.2.3-linux_x86_64-installer.run to install sequoiadb following steps in http://doc.sequoiadb.com/cn/sequoiadb-cat_id-1432191000-edition_id-302. I use standalone mode for convenience. And then I use sequoiasql-mysql-3.2.3-linux_x86_64-installer.run to install mysql instance following steps in http://doc.sequoiadb.com/cn/sequoiadb-cat_id-1521595270-edition_id-302.
